import os
import json
import argparse
from datetime import datetime
from PIL import Image
from tqdm import tqdm
import torch
from transformers import pipeline

class AIDetector:
    """
    Handles AI-powered object detection using OwlViT.
    """
    def __init__(self, model_id="google/owlvit-base-patch32", device=None):
        # Auto-detect device (GPU if available, else CPU)
        if device is None:
            self.device = "cuda" if torch.cuda.is_available() else "cpu"
        else:
            self.device = device
            
        print(f"[*] Loading AI Detector model ({model_id}) on {self.device}...")
        try:
            # device=0 maps to the first GPU, device=-1 maps to CPU
            self.detector = pipeline(
                model=model_id, 
                task="zero-shot-object-detection",
                device=0 if self.device == "cuda" else -1
            )
        except Exception as e:
            print(f"[!] Warning: Falling back to CPU due to initialization error: {e}")
            self.detector = pipeline(
                model=model_id, 
                task="zero-shot-object-detection",
                device=-1
            )

    def detect(self, image, labels, threshold=0.1):
        """Runs detection and returns filtered results with basic safety checks."""
        try:
            results = self.detector(image, candidate_labels=labels)
            return [r for r in results if r["score"] >= threshold]
        except Exception as e:
            print(f"[!] Detection inference error: {e}")
            return []

def create_coco_annotations(image_dir, output_file, category_name="helmet", detect=False, threshold=0.1, fallback=True, limit=0):
    """
    Scans a directory for images and creates a COCO formatted annotation JSON.
    Optionally use AI to detect objects.
    """
    valid_extensions = ('.png', '.jpg', '.jpeg', '.bmp', '.tiff', '.webp')
    
    # Base COCO structure
    coco_data = {
        "info": {
            "description": "AI-Enhanced dataset generated by Crawler",
            "url": "",
            "version": "1.1",
            "year": datetime.now().year,
            "contributor": "AI Crawler + OwlViT (Rider Detection)",
            "date_created": datetime.now().strftime("%Y/%m/%d")
        },
        "licenses": [{"id": 1, "name": "Unknown", "url": ""}],
        "images": [],
        "annotations": [],
        "categories": [{"id": 1, "name": category_name, "supercategory": "object"}]
    }
    
    if not os.path.exists(image_dir):
        print(f"[!] Error: Target directory '{image_dir}' does not exist.")
        return

    # Gather and sort images for consistency
    all_files = os.listdir(image_dir)
    images = sorted([f for f in all_files if f.lower().endswith(valid_extensions)])
    
    if limit > 0:
        images = images[:limit]
        
    if not images:
        print(f"[!] No valid images found in '{image_dir}'.")
        return

    # Initialize AI Detector if requested
    detector = None
    if detect:
        detector = AIDetector()

    print(f"[*] Processing {len(images)} images (AI Detection: {'ON' if detect else 'OFF'})...")

    annotation_id = 1
    for img_id, img_name in enumerate(tqdm(images, desc="Generating Annotations"), 1):
        img_path = os.path.join(image_dir, img_name)
        
        try:
            with Image.open(img_path) as img_raw:
                width, height = img_raw.size
                # Ensure image is in RGB for the model
                img = img_raw.convert("RGB") if img_raw.mode != "RGB" else img_raw
                
                # Register image in COCO
                coco_data["images"].append({
                    "id": img_id,
                    "width": int(width),
                    "height": int(height),
                    "file_name": img_name,
                    "license": 1,
                    "date_captured": datetime.fromtimestamp(os.path.getctime(img_path)).strftime("%Y-%m-%d %H:%M:%S")
                })
                
                hits = []
                if detect and detector:
                    # OwlViT works best with a set of descriptive labels
                    hits = detector.detect(img, labels=[f"a {category_name}", f"person on a {category_name}"], threshold=threshold)
                
                if hits:
                    for hit in hits:
                        box = hit["box"]
                        # Convert coordinates: OwlViT [xmin, ymin, xmax, ymax] -> COCO [x, y, w, h]
                        x1, y1, x2, y2 = float(box["xmin"]), float(box["ymin"]), float(box["xmax"]), float(box["ymax"])
                        w, h = x2 - x1, y2 - y1
                        
                        coco_data["annotations"].append({
                            "id": annotation_id,
                            "image_id": img_id,
                            "category_id": 1,
                            "segmentation": [[x1, y1, x2, y1, x2, y2, x1, y2]],
                            "area": float(w * h),
                            "bbox": [x1, y1, w, h],
                            "score": float(hit["score"]),
                            "iscrowd": 0
                        })
                        annotation_id += 1
                elif fallback:
                    # If nothing is detected or AI is off, create placeholder full-image box
                    coco_data["annotations"].append({
                        "id": annotation_id,
                        "image_id": img_id,
                        "category_id": 1,
                        "segmentation": [[0.0, 0.0, float(width), 0.0, float(width), float(height), 0.0, float(height)]],
                        "area": float(width * height),
                        "bbox": [0.0, 0.0, float(width), float(height)],
                        "iscrowd": 0
                    })
                    annotation_id += 1
            
        except Exception as e:
            print(f"[!] skipping image '{img_name}' due to error: {e}")

    # Final Save
    try:
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(coco_data, f, indent=4)
        print(f"\n[OK] successfully saved {len(coco_data['images'])} images and {annotation_id-1} annotations to '{output_file}'")
    except Exception as e:
        print(f"[!] Failed to save JSON file: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate COCO annotations with zero-shot AI detection.")
    parser.add_argument("--img-dir", type=str, default="data/raw/crawl/", help="Image source directory")
    parser.add_argument("--output", type=str, default="data/coco_annotations.json", help="Output JSON path")
    parser.add_argument("--category", type=str, default="motorcycle_rider", help="Category name to detect")
    parser.add_argument("--detect", action="store_true", help="Enable AI-powered object detection (OwlViT)")
    parser.add_argument("--threshold", type=float, default=0.1, help="Confidence threshold (0.0 to 1.0)")
    parser.add_argument("--no-fallback", action="store_false", dest="fallback", help="Don't create placeholder boxes for empty detections")
    parser.add_argument("--limit", type=int, default=0, help="Process only the first N images (0 for all)")
    parser.set_defaults(fallback=True)

    args = parser.parse_args()
    
    create_coco_annotations(
        image_dir=args.img_dir, 
        output_file=args.output, 
        category_name=args.category, 
        detect=args.detect, 
        threshold=args.threshold, 
        fallback=args.fallback,
        limit=args.limit
    )
